---
title: "Covid Phase Two Analysis
output: html_notebook
---

# preprocessing

```{r}
rm(list = ls())

# Download package tarball from CRAN archive
url <- "https://cran.r-project.org/src/contrib/Archive/zipcode/zipcode_1.0.tar.gz"
pkgFile <- "zipcode_1.0.tar.gz"
download.file(url = url, destfile = pkgFile)
# Install dependencies
install.packages(c("ada", "ipred", "evd","sjmisc"))
# Install package
install.packages(pkgs=pkgFile, type="source", repos=NULL)
# Delete package tarball
unlink(pkgFile)

# import libraries
library(ggplot2)
library(zipcode) # install only available through archive
library(maps)
library(ggpubr)
library("PerformanceAnalytics") # for chart correlation
library(usmap) # for plotting data us maps
library(scales) # for muted() function
library(tidyverse)
library(dplyr)
# library(memisc)
library(MASS)
```

```{r}
# load data

setwd("Y:/Lab_Projects/RA_Medical_covid19/behavioral/mdm_covid19_data")

data.all.2 <- read.csv("data_all_phase2_306sub_with_attitude.csv")
#tracker <- read.csv("all_states_avgs_2_clean.csv")
tracker <- all_state_avgs_2_clean
state_name <- read.csv("state_name.csv")
state_pops <- read.csv("state_pops2.csv")
data.all.2$age <- as.numeric(as.character(data.all.2$age)) + 17 # correct coding
```


```{r}
# merge tracker and state name
# colnames(state_name)[2] <- "state"
# tracker <- merge(tracker, state_name, by="state")


# separate into old and young (cutoff = 60yo)
data.all.2$is.young <- 1
data.all.2$is.young[data.all.2$age >= 60] = 0 
data.all.2$is.young <- as.factor(data.all.2$is.young)

# clean zipcode
data.all.2$zip_postal_code <- as.numeric(as.character(data.all.2$zip_postal_code))
data(zipcode)
data.all.2$zipcode<- clean.zipcodes(data.all.2$zip_postal_code)

# determine state names using zip - i dont think this is working
colnames(zipcode)
colnames(zipcode)[1] = "zipcode"
data.all.2 <- merge(data.all.2, zipcode, by="zipcode")

```
# sort data.all.2 into weeks corresponding w/ tracker 
```{r}
min(data.all.2$StartDate)
max(data.all.2$EndDate)

week <- c(1,2)
date <- c("2021-01-05", "2021-02-05")

timing <- data.frame(week,date)
timing$Week <- as.integer(timing$week)
tracker <- merge(tracker, timing, by="week")
```

# combine data.all.2 and tracker
```{r}
# change data type
tracker$state <- as.character(tracker$state)
tracker$week <- as.integer(as.character(tracker$week))

# match date in data.all.2 with week in tracker
data.all.2$Week <- NA
for (i in 1:nrow(data.all.2)) { 
  if (data.all.2$state[i] != "") {
    data.all.2$week[i] <-
      tracker$week[as.Date(data.all$StartDate[i], "%m/%d/%Y")>=as.Date(tracker$date) &
                        as.Date(data.all$StartDate[i], "%m/%d/%Y")<as.Date(tracker$date)+7 &
                        as.character(data.all$state[i]) == tracker$state]
  }
}

# combine data.all.2 and tracker by matching dates
data.all.2$Avg.positive.tests <- NA
data.all.2$Avg.deaths <- NA
data.all.2$Avg.current.hospitalized <- NA
data.all.2$week <- NA

# if within the week
for (i in 1:nrow(data.all.2)) {
    data.all.2$Avg.positive.tests[i] <-
      tracker$avg.pos.test[as.Date(data.all$StartDate[i],"%m/%d/%Y")>=as.Date(tracker$date) &
                        as.Date(data.all.2$StartDate[i],"%m/%d/%Y")<as.Date(tracker$date)+7 &
                        as.character(data.all$state[i]) == tracker$state]
    # first line = starting week of suvey > tracker date
    # second line = starting date of survey < tracker date + 7
    # AKA identify time interval 
    # third line = state of survey = matched to the tracker state
    # all conditions are linked by logical operator "&"

    data.all.2$Avg.deaths[i] <-
      tracker$avg.death[as.Date(data.all.2$StartDate[i],"%m/%d/%Y")>=as.Date(tracker$date) &
                        as.Date(data.all.2$StartDate[i],"%m/%d/%Y")<as.Date(tracker$date)+7 &
                        as.character(data.all.2$state[i]) == tracker$state]
    
    
    data.all.2$Avg.current.hospitalized[i] <-
      tracker$avg.hosp[as.Date(data.all.2$StartDate[i],"%m/%d/%Y")>=as.Date(tracker$date) &
                        as.Date(data.all.2$StartDate[i],"%m/%d/%Y")<as.Date(tracker$date)+7 &
                        as.character(data.all.2$state[i]) == tracker$state]
    
    data.all.2$week[i] <-
      tracker$week[as.Date(data.all.2$StartDate[i],"%m/%d/%Y")>=as.Date(tracker$date) &
                        as.Date(data.all.2$StartDate[i],"%m/%d/%Y")<as.Date(tracker$date)+7 &
                        as.character(data.all.2$state[i]) == tracker$state]
  }
  

```

